import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { toast } from "sonner";
import { Sparkles, AlertTriangle, Lightbulb, Target } from "lucide-react";

import { PageHeader, EmptyState } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { ScoreRing } from "@/components/score-ring";
import { useActiveDataset } from "@/lib/dataset-context";
import { getDataset, getDatasetRows } from "@/lib/api/datasets";
import { computeKpis } from "@/lib/api/analysis";
import { generateCeoBrief } from "@/lib/api/ai";
import { latestCeoBrief, saveCeoBrief } from "@/lib/api/persistence";
import { GenerationSourceBadge, GenerationSourceNotice } from "@/components/generation-source";
import { useIndustry } from "@/lib/industry-context";
import type { GenerationMeta } from "@/lib/api/types";

export const Route = createFileRoute("/ceo-brief")({
  head: () => ({ meta: [{ title: "CEO Brief, ExecutiveOS" }] }),
  component: CeoBriefPage,
});

// Split the summary paragraph into clean bullet points without losing any content.
function summaryPoints(summary: string): string[] {
  const points = summary
    .split(/(?<=[.!?])\s+(?=[A-Z0-9])/)
    .map((s) => s.trim())
    .filter(Boolean);
  return points.length ? points : [summary.trim()].filter(Boolean);
}

function CeoBriefPage() {
  const qc = useQueryClient();
  const { activeDatasetId } = useActiveDataset();
  const { industryId } = useIndustry();
  const [busy, setBusy] = useState(false);
  // Source of the most recent generation this session (DB-loaded briefs also
  // carry meta once migrated; this guarantees an honest label immediately).
  const [sessionMeta, setSessionMeta] = useState<GenerationMeta | undefined>(undefined);

  const { data: dataset } = useQuery({
    queryKey: ["dataset", activeDatasetId],
    queryFn: () => (activeDatasetId ? getDataset(activeDatasetId) : null),
    enabled: !!activeDatasetId,
  });
  const { data: rows = [] } = useQuery({
    queryKey: ["dataset-rows", activeDatasetId],
    queryFn: () => (activeDatasetId ? getDatasetRows(activeDatasetId) : []),
    enabled: !!activeDatasetId,
  });
  const { data: brief } = useQuery({
    queryKey: ["ceo-brief", activeDatasetId],
    queryFn: () => (activeDatasetId ? latestCeoBrief(activeDatasetId) : null),
    enabled: !!activeDatasetId,
  });

  async function regenerate() {
    if (!activeDatasetId || !dataset || !rows.length) return;
    setBusy(true);
    try {
      const kpis = computeKpis(rows, dataset.schema);
      const next = await generateCeoBrief({ dataset_id: activeDatasetId, kpis, rows, schema: dataset.schema, industry: industryId });
      setSessionMeta(next.meta);
      await saveCeoBrief(next);
      await qc.invalidateQueries({ queryKey: ["ceo-brief", activeDatasetId] });
      toast.success("CEO Brief regenerated");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed");
    } finally { setBusy(false); }
  }

  if (!activeDatasetId) {
    return (
      <>
        <PageHeader eyebrow="03, CEO Brief" title="Executive Summary" />
        <EmptyState title="Select a dataset" description="Pick a dataset in the sidebar to generate a CEO-grade summary." />
      </>
    );
  }

  return (
    <>
      <PageHeader
        eyebrow="03, CEO Brief"
        title="Executive Summary"
        description="A one-page executive view: business health, risks, opportunities, and the priority moves for the next quarter."
        actions={
          <Button onClick={regenerate} disabled={busy || !rows.length}>
            <Sparkles className={`h-4 w-4 mr-2 ${busy ? "animate-pulse" : ""}`} /> {busy ? "Generating…" : brief ? "Regenerate" : "Generate Brief"}
          </Button>
        }
      />

      {!brief ? (
        <EmptyState
          title="No brief yet"
          description="Generate your first CEO Brief, it takes a moment."
          action={<Button onClick={regenerate} disabled={busy || !rows.length}><Sparkles className={`h-4 w-4 mr-2 ${busy ? "animate-pulse" : ""}`} /> {busy ? "Generating…" : "Generate Brief"}</Button>}
        />
      ) : (
        <div className="space-y-6">
        <GenerationSourceNotice meta={sessionMeta ?? brief.meta} />
        <div className="grid lg:grid-cols-3 gap-6">
          <div className="executive-card rounded-xl p-6 lg:col-span-2">
            <div className="flex items-center justify-between mb-3 pb-3 border-b border-border/60">
              <div className="flex items-center gap-2">
                <span className="grid place-items-center h-7 w-7 rounded-md bg-secondary/15 border border-secondary/30 text-secondary font-display text-xs">CEO</span>
                <div>
                  <p className="text-[9px] uppercase tracking-[0.22em] text-muted-foreground">Generated By</p>
                  <p className="text-xs font-medium leading-tight">CEO Agent</p>
                </div>
              </div>
              <GenerationSourceBadge meta={sessionMeta ?? brief.meta} />
            </div>
            <p className="text-[11px] uppercase tracking-[0.22em] text-muted-foreground mb-3">Executive Summary</p>
            <ul className="space-y-2.5">
              {summaryPoints(brief.summary).map((point, i) => (
                <li key={i} className="flex gap-3 text-[15px] leading-relaxed text-foreground/90">
                  <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-secondary" />
                  <span>{point}</span>
                </li>
              ))}
            </ul>

            <div className="mt-8 grid sm:grid-cols-2 gap-6">
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <AlertTriangle className="h-4 w-4 text-destructive" />
                  <h3 className="font-display text-xl">Risks</h3>
                </div>
                <div className="space-y-3">
                  {brief.risks.map((r, i) => (
                    <div key={i} className="rounded-lg border border-border/60 p-3">
                      <div className="flex items-center justify-between">
                        <span className="text-sm font-medium">{r.title}</span>
                        <span className={`text-[10px] uppercase tracking-wider px-1.5 py-0.5 rounded ${
                          r.severity === "high" ? "bg-destructive/15 text-destructive" :
                          r.severity === "med" ? "bg-warning/15 text-warning" : "bg-muted text-muted-foreground"
                        }`}>{r.severity}</span>
                      </div>
                      <p className="text-xs text-muted-foreground mt-1.5">{r.description}</p>
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <div className="flex items-center gap-2 mb-3">
                  <Lightbulb className="h-4 w-4 text-secondary" />
                  <h3 className="font-display text-xl">Opportunities</h3>
                </div>
                <div className="space-y-3">
                  {brief.opportunities.map((o, i) => (
                    <div key={i} className="rounded-lg border border-border/60 p-3">
                      <div className="flex items-center justify-between">
                        <span className="text-sm font-medium">{o.title}</span>
                        <span className="text-[10px] uppercase tracking-wider px-1.5 py-0.5 rounded bg-success/15 text-success">{o.upside}</span>
                      </div>
                      <p className="text-xs text-muted-foreground mt-1.5">{o.description}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          <div className="space-y-6">
            <div className="executive-card rounded-xl p-6 flex flex-col items-center">
              <ScoreRing value={brief.health_score} label="Business Health" size={160}
                tone={brief.health_score >= 70 ? "success" : brief.health_score >= 45 ? "warning" : "destructive"} />
              <p className="text-[10px] text-muted-foreground text-center mt-3">Composite index of your real margin, growth, trend consistency and anomalies, a directional heuristic, not an audited score.</p>
            </div>

            <div className="executive-card rounded-xl p-6">
              <div className="flex items-center gap-2 mb-3">
                <Target className="h-4 w-4 text-secondary" />
                <h3 className="font-display text-xl">Priority Actions</h3>
              </div>
              <ol className="space-y-2 text-sm">
                {brief.priorities.map((p, i) => (
                  <li key={i} className="flex items-start gap-3 rounded-lg border border-border/60 p-3">
                    <span className="font-display text-lg text-secondary leading-none">{i + 1}</span>
                    <div className="flex-1">
                      <p className="font-medium">{p.title}</p>
                      <p className="text-xs text-muted-foreground mt-0.5">{p.owner} · {p.due}</p>
                    </div>
                  </li>
                ))}
              </ol>
            </div>

            <div className="executive-card rounded-xl p-6">
              <h3 className="font-display text-xl mb-3">Forecast Highlights</h3>
              <ul className="space-y-2 text-sm">
                {brief.forecast_highlights.map((h, i) => (
                  <li key={i} className="flex justify-between text-muted-foreground">
                    <span>{h.label}</span>
                    <span className="text-foreground font-medium">{h.value}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
        </div>
      )}
    </>
  );
}
