// Honest provenance indicators. These let any screen state plainly whether an
// artifact came from the live AI brain or the built-in (deterministic) analysis
// engine, and — when it fell back — exactly why. No screen should imply "AI"
// output it did not actually get from the model.
import { Sparkles, CircleAlert } from "lucide-react";
import type { GenerationMeta } from "@/lib/api/types";

const REASON_TEXT: Record<NonNullable<GenerationMeta["reason"]>, string> = {
  rate_limit:
    "Live AI is rate-limited — the AWS Bedrock request quota for this account is exhausted (try again shortly, or request a quota increase).",
  missing_key: "Live AI is not configured — AWS Bedrock credentials are missing or model access is not enabled on the server.",
  schema_invalid: "Live AI returned a malformed response, so the built-in analysis was used.",
  unavailable: "Live AI is temporarily unavailable.",
  budget: "The daily live-AI call budget for this server is spent (resets tomorrow, or raise LLM_DAILY_CALL_BUDGET).",
};

export function isAiSource(meta?: GenerationMeta): boolean {
  return !meta || meta.source === "ai";
}

/** Compact "Live AI" / "Built-in analysis" chip for a report header. */
export function GenerationSourceBadge({ meta }: { meta?: GenerationMeta }) {
  const ai = isAiSource(meta);
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-md px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.16em] border ${
        ai
          ? "bg-secondary/15 text-secondary border-secondary/30"
          : "bg-warning/15 text-warning border-warning/30"
      }`}
      title={ai ? "Generated by the live AWS Bedrock AI brain." : (meta?.reason ? REASON_TEXT[meta.reason] : "Built-in analysis.")}
    >
      {ai ? <Sparkles className="h-3 w-3" /> : <CircleAlert className="h-3 w-3" />}
      {ai ? "Live AI" : "Built-in analysis"}
    </span>
  );
}

/** Full-width notice shown only when output fell back to the built-in engine. */
export function GenerationSourceNotice({ meta }: { meta?: GenerationMeta }) {
  if (isAiSource(meta)) return null;
  const reason = meta?.reason ? REASON_TEXT[meta.reason] : "Live AI was unavailable.";
  return (
    <div className="flex items-start gap-2 rounded-lg border border-warning/30 bg-warning/10 px-4 py-3 text-xs text-warning-foreground">
      <CircleAlert className="h-4 w-4 shrink-0 text-warning mt-0.5" />
      <p className="leading-relaxed">
        <span className="font-medium">Showing built-in analysis.</span> {reason} The figures below are
        derived deterministically from your data, not written by the live model.
      </p>
    </div>
  );
}
