/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as ConsultantRouteImport } from './routes/consultant'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CeoBriefRouteImport } from './routes/ceo-brief'
import { Route as BoardroomRouteImport } from './routes/boardroom'
import { Route as ActionPlansRouteImport } from './routes/action-plans'
import { Route as AccuracyRouteImport } from './routes/accuracy'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantRoute = ConsultantRouteImport.update({
  id: '/consultant',
  path: '/consultant',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoBriefRoute = CeoBriefRouteImport.update({
  id: '/ceo-brief',
  path: '/ceo-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardroomRoute = BoardroomRouteImport.update({
  id: '/boardroom',
  path: '/boardroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionPlansRoute = ActionPlansRouteImport.update({
  id: '/action-plans',
  path: '/action-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AccuracyRoute = AccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/action-plans': typeof ActionPlansRoute
  '/boardroom': typeof BoardroomRoute
  '/ceo-brief': typeof CeoBriefRoute
  '/chat': typeof ChatRoute
  '/consultant': typeof ConsultantRoute
  '/decisions': typeof DecisionsRoute
  '/guide': typeof GuideRoute
  '/memory': typeof MemoryRoute
  '/reports': typeof ReportsRoute
  '/signals': typeof SignalsRoute
  '/simulator': typeof SimulatorRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/action-plans': typeof ActionPlansRoute
  '/boardroom': typeof BoardroomRoute
  '/ceo-brief': typeof CeoBriefRoute
  '/chat': typeof ChatRoute
  '/consultant': typeof ConsultantRoute
  '/decisions': typeof DecisionsRoute
  '/guide': typeof GuideRoute
  '/memory': typeof MemoryRoute
  '/reports': typeof ReportsRoute
  '/signals': typeof SignalsRoute
  '/simulator': typeof SimulatorRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/action-plans': typeof ActionPlansRoute
  '/boardroom': typeof BoardroomRoute
  '/ceo-brief': typeof CeoBriefRoute
  '/chat': typeof ChatRoute
  '/consultant': typeof ConsultantRoute
  '/decisions': typeof DecisionsRoute
  '/guide': typeof GuideRoute
  '/memory': typeof MemoryRoute
  '/reports': typeof ReportsRoute
  '/signals': typeof SignalsRoute
  '/simulator': typeof SimulatorRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accuracy'
    | '/action-plans'
    | '/boardroom'
    | '/ceo-brief'
    | '/chat'
    | '/consultant'
    | '/decisions'
    | '/guide'
    | '/memory'
    | '/reports'
    | '/signals'
    | '/simulator'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accuracy'
    | '/action-plans'
    | '/boardroom'
    | '/ceo-brief'
    | '/chat'
    | '/consultant'
    | '/decisions'
    | '/guide'
    | '/memory'
    | '/reports'
    | '/signals'
    | '/simulator'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/accuracy'
    | '/action-plans'
    | '/boardroom'
    | '/ceo-brief'
    | '/chat'
    | '/consultant'
    | '/decisions'
    | '/guide'
    | '/memory'
    | '/reports'
    | '/signals'
    | '/simulator'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccuracyRoute: typeof AccuracyRoute
  ActionPlansRoute: typeof ActionPlansRoute
  BoardroomRoute: typeof BoardroomRoute
  CeoBriefRoute: typeof CeoBriefRoute
  ChatRoute: typeof ChatRoute
  ConsultantRoute: typeof ConsultantRoute
  DecisionsRoute: typeof DecisionsRoute
  GuideRoute: typeof GuideRoute
  MemoryRoute: typeof MemoryRoute
  ReportsRoute: typeof ReportsRoute
  SignalsRoute: typeof SignalsRoute
  SimulatorRoute: typeof SimulatorRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant': {
      id: '/consultant'
      path: '/consultant'
      fullPath: '/consultant'
      preLoaderRoute: typeof ConsultantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo-brief': {
      id: '/ceo-brief'
      path: '/ceo-brief'
      fullPath: '/ceo-brief'
      preLoaderRoute: typeof CeoBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boardroom': {
      id: '/boardroom'
      path: '/boardroom'
      fullPath: '/boardroom'
      preLoaderRoute: typeof BoardroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-plans': {
      id: '/action-plans'
      path: '/action-plans'
      fullPath: '/action-plans'
      preLoaderRoute: typeof ActionPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accuracy': {
      id: '/accuracy'
      path: '/accuracy'
      fullPath: '/accuracy'
      preLoaderRoute: typeof AccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccuracyRoute: AccuracyRoute,
  ActionPlansRoute: ActionPlansRoute,
  BoardroomRoute: BoardroomRoute,
  CeoBriefRoute: CeoBriefRoute,
  ChatRoute: ChatRoute,
  ConsultantRoute: ConsultantRoute,
  DecisionsRoute: DecisionsRoute,
  GuideRoute: GuideRoute,
  MemoryRoute: MemoryRoute,
  ReportsRoute: ReportsRoute,
  SignalsRoute: SignalsRoute,
  SimulatorRoute: SimulatorRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
